namespace Freql.Tools.CodeGeneration

open System

module Boilerplate =

    module Header =

        let lines =
            [ "//----------------------------------------------------------------------------------- "
              "// <auto-generated>                                                                   "
              "//     This code was generated via Freql.Tools (https://github.com/mc738/Freql).      "
              "//                                                                                    "
              "//     Manual changes to this file may cause unexpected behavior in your application. "
              "//     Manual changes to this file will be overwritten if the code is regenerated.    "
              "// </auto-generated>                                                                  "
              "//----------------------------------------------------------------------------------- " ]

    module Comments =

        let freqlRemark (timestamp: DateTime) =
            [ "/// <remarks>"
              $"/// This record was generated via Freql.Tools on {timestamp}"
              "/// </remarks>" ]
